services:
  - type: web
    name: fazenda-app
    runtime: node
    plan: free
    buildCommand: npm install && cd client && npm install --include=dev && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
